# Generated by Django 5.0.6 on 2024-07-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_no',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
