# Generated by Django 5.0.6 on 2024-07-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_booking_total_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='uder_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='uder_id',
            new_name='user_id',
        ),
    ]
