# Generated by Django 5.0.6 on 2024-07-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_uder_id_booking_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=10, null=True),
        ),
    ]
