# Generated by Django 5.0.6 on 2024-07-17 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='package_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app1.packages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
